First version of "import" page is ready
alix-tz/escriptorium-tutorial pull request #27
Opened 2023-02-01 16:06 UTC by alix-tz

Some "todo" remaining: left for later in #24 #25 and #26

2023-02-08 14:14 UTC, HugoSchtr requested changes
It looks very good, good job! I've only made a few comments on phrasing and references!

2023-02-08 14:15 UTC, HugoSchtr commented
Well, I have requested changes, but I didn't know that it would block merging. :sweat_smile: Of course, no changes are required, my comments were only suggestions. :+1:

2023-02-09 08:59 UTC, FloChiff commented
On top of the comments by Hugo that I also mostly agree to (I am not sure about the place of the mapping part), here are the typos I saw in the document : 
- l. 42 --> I think the correct term is "manifest" and not "manifesto" ; I also think that "metadata" is plural and not singular so it should be "are visible" instead of "is visible"
- l. 51 --> I think it should be a present "can" and not a conditional "could" as you also already used "can" right before
- l. 79 --> it should be "Known" and not "Knwon"
- l. 83 --> "useful" only has one 'l' at the end and "targeting" is written with only one 't' at the end

Also, around the lines 25-30 about the import of images, I have a recommendation for the tip related to a problem I sometimes encountered but you don't have to add it if you don't find it relevant --> when I upload big load of images (like 100 at the same time), it can make eScriptorium bug sometimes and it will not be able to upload one or two images in the mix, even though it load the images before and after. This is not a big issue as you can upload them afterwards but when you care about image orders, this is frustrating. So the advice regarding that would be to upload by little chunk (25 by 25 or something like that).

2023-02-09 11:05 UTC, FloChiff reviewed
On top of the comments by Hugo that I also mostly agree to (I am not sure about the place of the mapping part), here are the typos I saw in the document :

    l. 42 --> I think the correct term is "manifest" and not "manifesto" ; I also think that "metadata" is plural and not singular so it should be "are visible" instead of "is visible"
    l. 51 --> I think it should be a present "can" and not a conditional "could" as you also already used "can" right before
    l. 79 --> it should be "Known" and not "Knwon"
    l. 83 --> "useful" only has one 'l' at the end and "targeting" is written with only one 't' at the end

Also, around the lines 25-30 about the import of images, I have a recommendation for the tip related to a problem I sometimes encountered but you don't have to add it if you don't find it relevant --> when I upload big load of images (like 100 at the same time), it can make eScriptorium bug sometimes and it will not be able to upload one or two images in the mix, even though it load the images before and after. This is not a big issue as you can upload them afterwards but when you care about image orders, this is frustrating. So the advice regarding that would be to upload by little chunk (25 by 25 or something like that).

2023-02-09 13:10 UTC, alix-tz commented
Thank you both for your feedback! They are all very good remarks, I'll make the changes

2023-02-13 10:48 UTC, alix-tz commented on docs/walkthrough_import.md
> +    When importing XML files generated with other tools such as Transkribus, it can be usefull to run a segmentation task targetting only the line masks <!-- todo: add link to mask recalculation -->
yes, I think it's a good idea to point to external resources

2023-02-13 10:54 UTC, alix-tz commented
> Also, around the lines 25-30 about the import of images, I have a recommendation for the tip related to a problem I sometimes encountered but you don't have to add it if you don't find it relevant --> when I upload big load of images (like 100 at the same time), it can make eScriptorium bug sometimes and it will not be able to upload one or two images in the mix, even though it load the images before and after. This is not a big issue as you can upload them afterwards but when you care about image orders, this is frustrating. So the advice regarding that would be to upload by little chunk (25 by 25 or something like that).

@FloChiff : you know that you can reorder images by dragging the "image" card in `/images`?

2023-02-13 10:59 UTC, FloChiff commented
> 

@alix-tz Well I do now !!! I discover a new thing everyday about eSc thanks to this tutorial 😄 !!!

2023-02-13 11:06 UTC, alix-tz commented
I had to rebase because the config in mkdocs.yml was not up-to-date (the rendering of admonitions was not good).

2023-02-13 11:09 UTC, alix-tz commented
> Well, I have requested changes, but I didn't know that it would block merging. 😅 Of course, no changes are required, my comments were only suggestions. 👍

@HugoSchtr I don't understand why it's still requesting the validation of the reviews...

2023-02-13 11:19 UTC, HugoSchtr approved these changes
😎

2023-02-21 14:28 UTC, FloChiff approved these changes

2023-02-21 15:40 UTC, merged